"""empty message

Revision ID: 0419913bcb38
Revises: 
Create Date: 2024-04-24 12:03:06.246943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0419913bcb38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('weekday_price', sa.Integer(), nullable=True),
    sa.Column('weekend_price', sa.Integer(), nullable=True),
    sa.Column('strict_dress', sa.Boolean(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('slope', sa.Float(), nullable=True),
    sa.Column('course_length', sa.Integer(), nullable=True),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('designer', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_table('golfer',
    sa.Column('golfer_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('golfer_age', sa.Integer(), nullable=False),
    sa.Column('handicap', sa.Float(), nullable=True),
    sa.Column('right_handed', sa.Boolean(), nullable=True),
    sa.Column('alcohol', sa.Boolean(), nullable=True),
    sa.Column('legal_drugs', sa.Boolean(), nullable=True),
    sa.Column('smoker', sa.Boolean(), nullable=True),
    sa.Column('gambler', sa.Boolean(), nullable=True),
    sa.Column('tees', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('music', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('golfer_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teetime',
    sa.Column('teetime_id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('teetime_date', sa.String(), nullable=False),
    sa.Column('teetime_time', sa.String(), nullable=False),
    sa.Column('space_remaining', sa.Integer(), nullable=False),
    sa.Column('golfer_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.course_id'], ),
    sa.ForeignKeyConstraint(['golfer_id'], ['golfer.golfer_id'], ),
    sa.PrimaryKeyConstraint('teetime_id')
    )
    op.create_table('golfer_comment',
    sa.Column('golfer_comment_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('golfer_id', sa.Integer(), nullable=False),
    sa.Column('teetime_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['golfer_id'], ['golfer.golfer_id'], ),
    sa.ForeignKeyConstraint(['teetime_id'], ['teetime.teetime_id'], ),
    sa.PrimaryKeyConstraint('golfer_comment_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('golfer_comment')
    op.drop_table('teetime')
    op.drop_table('golfer')
    op.drop_table('course')
    # ### end Alembic commands ###
