"""empty message

Revision ID: 8b9513fc735f
Revises: 0419913bcb38
Create Date: 2024-04-24 15:00:10.043032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b9513fc735f'
down_revision = '0419913bcb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('tokenExp', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golfer', schema=None) as batch_op:
        batch_op.drop_column('tokenExp')
        batch_op.drop_column('token')

    # ### end Alembic commands ###
