"""fix course table

Revision ID: c88f020fc8c0
Revises: 
Create Date: 2024-04-23 16:09:53.865026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c88f020fc8c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_column('course_id')

    with op.batch_alter_table('golfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('alcohol', sa.Boolean(), nullable=True))
        batch_op.drop_column('golfer_id')
        batch_op.drop_column('pw_hash')
        batch_op.drop_column('alcholol')

    with op.batch_alter_table('golfer_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('golfer_comment_golfer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('golfer_comment_teetime_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'golfer', ['golfer_id'], ['id'])
        batch_op.create_foreign_key(None, 'teetime', ['teetime_id'], ['id'])
        batch_op.drop_column('comment_id')

    with op.batch_alter_table('teetime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('teetime_golfer_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('teetime_course_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'course', ['course_id'], ['id'])
        batch_op.create_foreign_key(None, 'golfer', ['golfer_id'], ['id'])
        batch_op.drop_column('teetime_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teetime', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teetime_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('teetime_course_id_fkey', 'course', ['course_id'], ['course_id'])
        batch_op.create_foreign_key('teetime_golfer_id_fkey', 'golfer', ['golfer_id'], ['golfer_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('golfer_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('golfer_comment_teetime_id_fkey', 'teetime', ['teetime_id'], ['teetime_id'])
        batch_op.create_foreign_key('golfer_comment_golfer_id_fkey', 'golfer', ['golfer_id'], ['golfer_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('golfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alcholol', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('pw_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('golfer_id', sa.INTEGER(), server_default=sa.text("nextval('golfer_golfer_id_seq'::regclass)"), autoincrement=True, nullable=False))
        batch_op.drop_column('alcohol')
        batch_op.drop_column('password')
        batch_op.drop_column('id')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###
