"""empty message

Revision ID: d3750e482ea1
Revises: 
Create Date: 2024-04-24 10:29:41.369383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3750e482ea1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alcohol', sa.Boolean(), nullable=True))
        batch_op.drop_column('alchohol')

    with op.batch_alter_table('golfer_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('golfer_comment_id', sa.Integer(), nullable=False))
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('golfer_comment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), autoincrement=True, nullable=False))
        batch_op.drop_column('golfer_comment_id')

    with op.batch_alter_table('golfer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alchohol', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('alcohol')

    # ### end Alembic commands ###
